### ISSUE TITLE
build binaries on travis

### ISSUE THREAD

**Issue by TeddyDD** [alexherbo2/batch#3]
I wonder if you would be interested in setting up automated binary builds on travis. Complied binaries could be pushed to gh releases (for example every time you push new tag to the repo).

I created Alpine docker file and modified .travis.yml in my [dockerfile](https://github.com/TeddyDD/batch/tree/dockerfile) branch. Currently builds are [failing](https://travis-ci.org/TeddyDD/batch/builds/589604912), I haven't figure out why yet.

Building from Alpine container are statically linked, stripped and packed with upx so they should work everywhere (and they are tiny, around 400kb)

**Comment by alexherbo2** [comment]
I don’t even know how to make a release. xD

Can you explain me how to do (manually / automatically) and how is it working?

**Comment by TeddyDD** [comment]
Well, when you push git tags to GH then they appear in the [releases](https://github.com/alexherbo2/batch/releases). You can create „release” from tagged commit by adding some notes and attaching binary resources.

My idea is to build batch on every commit on travis as usually. When you push new tag then travis would also attach compiled binary to GH „release”.

**Comment by alexherbo2** [comment]
Yes I’m in.

**Comment by alexherbo2** [comment]
@TeddyDD Do you want a push access for experimenting?

**Comment by TeddyDD** [comment]
No, I can experiment on my fork, I gotta figure out why builds fail on Travis first
