### ISSUE TITLE
Comparison with vidir

### ISSUE THREAD

**Issue by JJK96** [alexherbo2/batch#5]
I was looking for other programs that have similar functionality and I found [vidir](https://github.com/trapd00r/vidir).
Maybe it's good to have a section in the readme with similar programs and differences from them.

For example, batch and vidir both are able to remove and rename files in an editor. But batch is more flexible since you can define the commands to execute yourself.

**Comment by alexherbo2** [comment]
A document like: https://github.com/alexherbo2/krabby/blob/master/docs/alternatives.md?

**Comment by alexherbo2** [comment]
https://youtu.be/guHrH8NlfFs

**Comment by alexherbo2** [comment]
@JJK96 I am not interested to do it myself, but I am keen to merge.
